version: "3.9"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/todo
      CLIENT_URL: http://localhost:5173
    depends_on:
      - db
    ports:
      - "3000:3000"

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      - api
    ports:
      - "5173:80"
